// Mô hình 2 lớp: LỚP 1 (phân loại level) dùng CHUNG cho A1/A1-A2/B1 qua bảng tham chiếu
// này — trước đây mỗi prompt chỉ mô tả quy tắc chung bằng lời văn cho AI tự suy luận,
// không có danh sách cụ thể để đối chiếu, dẫn tới cùng 1 cụm bị gắn level khác nhau tuỳ
// câu. LỚP 2 (độ chi tiết hiển thị: tách từng từ / cụm công thức / đoạn theo nghĩa) vẫn
// khác nhau theo từng nhánh bên dưới, KHÔNG đụng vào bảng này. B2 không dùng bảng này
// (giữ nguyên theo yêu cầu, prompt B2 đã có ví dụ CEFR đa dạng sẵn).
export const CEFR_LEVEL_REFERENCE = `CEFR LEVEL REFERENCE TABLE — use this to assign "level" for EVERY word/phrase. Check here FIRST before relying on general judgment. If a chunk isn't listed exactly, match it to the closest PATTERN/STRUCTURE type below (e.g. an unlisted basic phrasal verb → same group as the basic phrasal verbs listed under A2):
- A1: familiar set phrases (good morning, thank you, excuse me, how are you, nice to meet you, see you later, of course, I'm sorry, I don't know, a lot of, every day, next week, last year); basic prepositional phrases (at home, at work, at school, in bed, in class, on the table, under the chair, next to the door); simple noun phrases (my mother, your friend, a big house, the red car, an old man); simple verb phrases (can swim, can speak English, want to eat, like playing football, have breakfast); time expressions (every day, every week, this morning, last night, next month, at six o'clock).
- A2: "be going to", "have to", "would like to", "there is/are", some/any, too...to, enough to, adjective+to-V, adjective+preposition; common verb+preposition combos, basic phrasal verbs (wake up, get up); prepositional verbs (depend on, belong to, listen to, insist on, apologize for); basic comparison (as...as, more...than, less...than); quantity phrases (a few, a little, a great deal of, plenty of, a large number of, lots of); fixed noun phrases (a piece of advice, a bit of, a number of, the majority of).
- B1: verb patterns (decide to do, stop doing/to do, remember doing/to do); phrasal verbs (give up, find out, look after, carry on); advanced modals (should/must/might have done); passive voice (is built, was made, has been written); simple relative clauses (the man who..., the book that...); because/although/if clauses; verb+object+to-V (ask him to come, tell me to wait, force them to leave); verb+object+bare infinitive — IMPORTANT: these use short common words (let, go, make, laugh) but the PATTERN itself (verb+object+bare infinitive, no "to") is B1-level grammar, NOT A2 — do not downgrade just because the individual words look simple: let him go, make me laugh, have someone clean; fixed adjective+preposition (afraid of, interested in, proud of, responsible for, good at, familiar with, similar to); fixed prepositional phrases (in charge of, in front of, because of, due to, according to, instead of, in spite of, on behalf of).
- B2: participle/infinitive/gerund phrases, noun clauses, reduced relative clauses, perfect/passive infinitives, cleft sentences, basic inversion, parallel structure, correlative conjunctions, complex phrasal verbs, fixed expressions, collocations; verb+object+V-ing (catch him cheating, keep me waiting, leave the water running); verb+object+past participle (get it repaired, have my hair cut, leave the door locked); advanced verb patterns — "somebody"/"doing" below are PLACEHOLDERS that must match ANY person (him/her/them/the fire/the students/etc.) and ANY -ing verb, not just the literal words "somebody"/"doing": prevent somebody from doing (e.g. "prevent him from leaving", "prevent the fire from spreading", "prevent students from cheating"), accuse somebody of doing (e.g. "accuse her of lying"), remind somebody to do (e.g. "remind me to call"), persuade somebody to do (e.g. "persuade them to stay"); special structures (It is...that..., It takes..., It seems..., It appears...); strong collocations (make a decision, take a break, heavy rain, strong coffee, pay attention).
- C1/C2 (reference only — still tag honestly if a structure clearly belongs here, do NOT force it down to B2): absolute phrases, advanced inversion, ellipsis, nominalisation, discourse markers, academic collocations; idioms (once in a blue moon, break the ice, hit the sack, cost an arm and a leg); advanced academic writing structures.
Assign the level that TRUTHFULLY matches the word/phrase's real difficulty using this table — do NOT simplify the level just because the current analysis mode targets beginners.`;
